spring:
  profiles:
    include: vk, instagram
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
  main:
    web-application-type: none
telegram:
  admin-uid: 124275139
