spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  port: 8080
  shutdown: graceful